name: Update JSON

on:
  schedule:
    - cron: '0 0 * * 0' # This will run the action every Sunday at midnight
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Update JSON
      run: python generate_data.py

    - name: Commit and push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add prices.json
        git commit -m "Update prices.json" -a
        git push